### ISSUE TITLE
Poster find problem

### ISSUE THREAD

**Issue by EvgenKostenko** [olegkovalov/movie_search#5]
When I search 0000 it not return image just print my search query 

![screen shot 2015-09-16 at 18 55 29](https://cloud.githubusercontent.com/assets/9476950/9910218/ac2c4004-5ca4-11e5-8fbd-85d0201ef902.png)

And it stored in history?

![screen shot 2015-09-16 at 18 55 04](https://cloud.githubusercontent.com/assets/9476950/9910240/bba4a31e-5ca4-11e5-9dfd-8cfd5ff13210.png)

**Comment by olegkovalov** [comment]
It prints film title. If film has a poster it prints title and poster. I asked about this detail in technical requirements. 

http://www.omdbapi.com/?t=0000&plot=short&r=json
Response is:
{"Title":"0000","Year":"2011","Rated":"N/A","Released":"N/A","Runtime":"N/A","Genre":"Sci-Fi","Director":"Eddie Alcazar","Writer":"Eddie Alcazar","Actors":"Larry Cedar, Kevin McCorkle, Aaron Behr, Christopher Dempsey","Plot":"One mans creation will help form a collective consciousness.","Language":"N/A","Country":"N/A","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"N/A","imdbVotes":"N/A","imdbID":"tt1710927","Type":"N/A","Response":"True"}

It prints Title
